eventsource:
  type: 
  eventName: 
  jsonBody: 
  name: 
  queue: 
  region: 
  waitTimeSeconds: 
sensors: 
- argoWorkFlow:
    configmap:
      key: 
      name: 
    operation: 
    parameters:
      dest: 
      src:
        dataKey: 
        dependencyName: 
    source: 
  dependencies:
    eventName: 
    eventSourceName: 
    name: 
  name: 
  triggers:
    template:
      name: 
      type: 
serviceAccount:
  create: 
workloadIdentity:
  create: 
  aws:
    accountId: 
    oidcProvider: 