
# workflow id
id: ""
# workload instance (resource apply name)
instance: "1"
component: ""
partOf: ""
#managedBy: ""
createdBy: ""
project: ""

# global
infra: ~
kube: ~

# identity
identity:
  create: true

# eventsource
type: ""
properties: {}

# workflows
workflows: []

sensor:
  clusterRoles:
    - argo-workflows-role

kafka:
  connectionBackoff:
    duration: 10s
    steps: 5
    factor: 2
    jitter: 0.2