eventsource:
  type: sqs
  eventName: example
  jsonBody: true
  name: sqs-es
  queue: argo-event-source-demo
  region: us-east-1
  waitTimeSeconds: 20
sensors: 
- argoWorkFlow:
    configmap:
      key: template
      name: workflow-whalesay-2
    operation: submit
    parameters:
      dest: spec.arguments.parameters.0.value
      src:
        dataKey: body
        dependencyName: test-dep
    source: configmap
  dependencies:
    eventName: example
    eventSourceName: sqs-es
    name: test-dep
  name: sensor-sqs
  triggers:
    template:
      name: sqs-workflow
      type: argoWorkflow
serviceAccount:
  create: true
workloadIdentity:
  create: true
  aws:
    accountId: "554248189203"
    oidcProvider: oidc.eks.us-east-1.amazonaws.com/id/62548ADFE180A81DC1D790B2E2B5995C
namespace: gravity-system