eventsource:
  properties:
    jsonBody: 
    queue:
    waitTimeSeconds: 
# sensor:
#   - create: false
#     values: 
#     - name: ""
#       options:
#         argoWorkFlow:
#           configmap:
#             key: template
#             name: workflow-whalesay-2
#           operation: submit
#           parameters:
#             dest: spec.arguments.parameters.0.value
#             src:
#               dataKey: body
#               dependencyName: test-dep
#           source: configmap
#         dependencies:
#           eventName: example
#           eventSourceName: sqs-es
#           name: test-dep
#         triggers:
#           template:
#             name: sqs-workflow
#             type: argoWorkflow
workloadIdentity:
  create: true
  aws:
    accountId: 
    oidcProvider: 
namespace: gravity-system

sensor: {}
  # configmap:
  #   name: 
  #   key: 

aws:
  region: us-east-1