eventsource:
  type: sqs
  eventName: example
  jsonBody: true
  name: sqs-es
  queue: argo-event-source-demo
  region: us-east-1
  waitTimeSeconds: 20
sensors: {}
workloadIdentity:
  create: true
  aws:
    accountId: "554248189203"
    oidcProvider: oidc.eks.us-east-1.amazonaws.com/id/62548ADFE180A81DC1D790B2E2B5995C
namespace: gravity-system