eventsource:
  properties:
    jsonBody:
    queue: 
    waitTimeSeconds: 
workloadIdentity:
  create: 
  aws:
    accountId: ""
    oidcProvider: 
namespace: dev

sensor: {}
  # configmaps:
  #   - name: 
  #     key: 
  #   - name: 
  #     key: 

aws:
  region: us-east-1
