{{- range $index, $secret := .Values.secrets }}
{{- if $secret.spec.volumes }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $secret.id }}-vol
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider: {{ lower $.Values.infra.provider }}
  {{- if eq "Azure" $.Values.infra.provider }}
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{ $secret.storeID }}
    objects: |
      array:
        {{- range $vi, $vol := $secret.spec.volumes }}
        - |
          objectName: {{ $secret.externalName }}
          objectType: secret
          {{- if $vol.fileName }}
          objectAlias: {{ $vol.fileName }}
          {{- else }}
          objectAlias: {{ $secret.spec.ref.name }}-{{ $vi }}
          {{- end }}
        {{- end }}
    tenantId: {{ $.Values.infra.props.tenantId }}
  {{- end }}
  {{- if eq "AWS" $.Values.infra.provider }}
  parameters:
    region: {{ $.Values.infra.region }}
    objects: |
      {{- range $vi, $vol := $secret.spec.volumes }}
      - objectName: {{ $secret.externalName }}
        objectType: secretsmanager
        {{- if $vol.fileName }}
        objectAlias: {{ $vol.fileName }}
        {{- else }}
        objectAlias: {{ $secret.spec.ref.name }}-{{ $vi }}
        {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}