{{- range $index, $secret := .Values.secrets }}
{{- if or $secret.spec.envAll $secret.spec.env}}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $secret.id }}-env
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider: {{ lower $.Values.infra.provider }}
  secretObjects:
    - data:
      {{- range $sei, $envAll := $secret.spec.envAll }}
      {{- range $sei, $key := $envAll.keys }}
        - key: {{ $key }}
          objectName: {{ $key }}
      {{- end }}
      {{- end }}
      {{- range $sei, $env := $secret.spec.env }}
        - key: {{ $env.key }}
          objectName: {{ $env.key }}
      {{- end }}
      secretName: {{ $secret.id }}-env
      type: Opaque
  {{- if eq "Azure" $.Values.infra.provider }}
  parameters:
    usePodIdentity: "true"
    keyvaultName: {{ $secret.storeID }}
    objects: |
      array:
        - |
          objectName: {{ $secret.externalName }}
          objectType: secret
          objectAlias: {{ $secret.spec.ref.name }}
    tenantId: {{ $.Values.infra.props.tenantId }}
  {{- end }}
  {{- if eq "AWS" $.Values.infra.provider }}
  parameters:
    region: {{ $.Values.infra.region }}
    objects: |
      - objectName: {{ $secret.externalName }}
        objectType: secretsmanager
        objectAlias: {{ $secret.spec.ref.name }}
        jmesPath:
          {{- range $sei, $envAll := $secret.spec.envAll }}
          {{- range $sei, $key := $envAll.keys }}
          - path: {{ $key }}
            objectAlias: {{ $key }}
          {{- end }}
          {{- end }}
          {{- range $sei, $env := $secret.spec.env }}
          - path: {{ $env.key }}
            objectAlias: {{ $env.key }}
          {{- end }}
  {{- end }}
{{- end }}
{{- end }}