{{- if eq "Volcano" .Values.engine }}
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: {{ .Values.name }}
spec:
  schedulerName: volcano
  policies:
  - event: PodEvicted
    action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  queue: {{ .Values.task.options.queue.value }}
  tasks:
  - name: {{ .Values.name }}
    replicas: {{ .Values.task.options.minAvailable.value }}
    maxRetry: {{ .Values.task.options.maxRetry.value }}
    template:
      spec:
        containers:
        - image: {{ .Values.task.image.name }}:{{ .Values.task.image.tag }}
          imagePullPolicy: Always
          {{- if .Values.task.args }}
          command:
          {{- range $a := .Values.task.args }}
          - {{ $a }}
          {{- end }}
          {{- end }}
          name: {{ .Values.name }}
          resources:
            requests:
              cpu: {{ .Values.task.capacity.resources.requests.cpu }}
              memory: {{ .Values.task.capacity.resources.requests.memory }}
          {{- if .Values.task.env }}
          env:
          {{- range $name ,$val := .Values.task.env }}
          - name: {{ $name }}
            value: {{ $val }}
          {{- end }}
          {{- end }}
          {{- if .Values.volumes }}
          volumeMounts:
          {{- range $i ,$vol := .Values.volumes }}
          - name: {{ $vol.spec.ref.name }}-{{$i}}
            mountPath: {{ $vol.spec.mountPath }}
          {{- end }}
          {{- end }}
        restartPolicy: OnFailure
        {{- if .Values.volumes }}
        volumes:
        {{- range $i ,$vol := .Values.volumes }}
        - persistentVolumeClaim: 
            claimName: {{ $vol.spec.ref.name }}
          name: {{ $vol.spec.ref.name }}-{{$i}}
        {{- end }}
        {{- end }}
{{- end }}