apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  generateName: step-job-1-
  name: {{ .Values.name }}
spec:
  schedulerName: volcano
  policies:
  - event: PodEvicted
    action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
#   {{- if .Values.volcano.maxRetry }}
#   maxRetry: {{ .Values.volcano.maxRetry  }}
#   {{- end }}
  queue: default
  tasks:
  {{- range $i, $container := .Values.containers }}
  - name: "{{ $i }}"
    replicas: {{ $container.containerReplica.desired }}
    template:
      spec:
        containers:
        - image: {{ $container.image.name }}:{{ $container.image.tag }}
          imagePullPolicy: Always
          {{- if $container.args }}
          command:
          {{- range $c := $container.args }}
          - {{ $c }}
          {{- end }}
          {{- end }}
          name: "{{ $i }}"
          resources:
            requests:
              cpu: {{ $container.resources.requests.cpu }}
              memory: {{ $container.resources.requests.memory }}
        restartPolicy: OnFailure
  {{- end }}