apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: nginx
  name: nginx
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
 nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
