{{- $appname := include "gravity-workflow.name" . }}

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ $appname }}
spec:
  {{ .Values.eventsource.type }}:
    default:
      {{- range $key, $val := .Values.eventsource.properties }}
      {{- if eq $key "queue"}}
      queue: {{ (split ":" $val)._5 }}
      {{- else }}
      {{ $key }}: {{ $val }}
      {{- end}}
      {{- end }}
      {{- if eq $.Values.eventsource.type "sqs" }}
      # temporary block...
      accessKey:
        key: accesskey
        name: aws-secret-dev
      secretKey:
        key: secretkey
        name: aws-secret-dev
      {{- end }}
      {{- if eq $.Values.eventsource.type "azureEventsHub"}}
      sharedAccessKeyName:
        name: {{ .Values.eventsource.sharedAccessKeyName.name }} 
        key: {{ .Values.eventsource.sharedAccessKeyName.key }} 
      sharedAccessKey:
        name: {{ .Values.eventsource.sharedAccessKey.name }} 
        key: {{ .Values.eventsource.sharedAccessKey.key }} 
      {{- end }}
  template:
    metadata:
      labels:
      {{- include "gravity-workflow.labels" $ | nindent 8 }}
    # serviceAccountName: {{ $appname }}-eventsource
