{{- $appname := include "gravity-workflow.name" . }}

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ $appname }}
spec:
  {{- if eq $.Values.type "sqs" }}
  sqs:
    default:
      {{- range $key, $val := .Values.eventsource.properties }}
      {{- if eq $key "queue"}}
      queue: {{ (split ":" $val)._5 }}
      {{- else }}
      {{ $key }}: {{ $val }}
      {{- end}}
      {{- end }}
      # temporary block...
      accessKey:
        key: accesskey
        name: aws-secret-dev
      secretKey:
        key: secretkey
        name: aws-secret-dev
  {{- end }}
  {{- if eq $.Values.type "azureEventsHub" }}
  azureEventsHub:
    default:
      {{- range $key, $val := .Values.eventsource.properties }}
      {{ $key }}: {{ $val }}
      {{- end }}
      sharedAccessKeyName:
        name: {{ .Values.azuresecret.sharedAccessKeyName.name }} 
        key: {{ .Values.azuresecret.sharedAccessKeyName.key }} 
      sharedAccessKey:
        name: {{ .Values.azuresecret.sharedAccessKey.name }} 
        key: {{ .Values.azuresecret.sharedAccessKey.key }} 
  {{- end }}
  {{- if eq $.Values.type "calendar" }}
  calendar:
    default:
      {{- toYaml .Values.properties | nindent 6 }}
  {{- end }}
  {{- if eq $.Values.type "github" }}
  service:
    ports:
      - name: default
        port: 12000
        targetPort: 12000
  github:
    default:
      repositories:
        owner: {{ .Values.eventsource.github.owner }}
        repositories:
          {{- range $val := .Values.eventsource.github.repositories }}
          - {{ $val }}
          {{- end }}
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: {{ .Values.eventsource.github.url }}
      events:
        {{- range $val := .Values.eventsource.github.events }}
        - {{ $val | quote }}
        {{- end }}
      apiToken:
        name: {{ .Values.githubsecret.apiToken.name }}
        key: {{ .Values.githubsecret.apiToken.key }}
      insecure: true
      active: true
      contentType: json
  {{- end }}
  {{- if eq $.Values.type "redis" }}
  redis:
    default:
      hostAddress: {{ .Values.eventsource.redis.hostAddress  }}
      db: {{ .Values.eventsource.redis.db  }}
      channels:
      {{- range $val := .Values.eventsource.redis.channels }}
      - {{ $val }}
      {{- end }}
      password:
        name: {{ .Values.redisSecret.name  }}
        key: {{ .Values.redisSecret.key  }}
      namespace: {{ .Values.redisSecret.namespace  }}
  {{- end }}
  {{- if eq $.Values.type "kafka" }}
  kafka:
    default:
      {{- range $key, $val := .Values.eventsource.properties }}
      {{ $key }}: {{ $val | quote }}
      {{- end}}
      {{- if .Values.kafka }}
      connectionBackoff:
        {{- range $key, $val := .Values.kafka.connectionBackoff }}
        {{ $key }}: {{ $val }}
        {{- end}}
      sasl:
        {{- toYaml $.Values.kafka.sasl | nindent 8}}
      tls:
        insecureSkipVerify: true
      {{- end}}
  {{- end }}
  {{- if eq $.Values.type "resource" }}
  resource:
    default:
      {{- range $key, $val := .Values.eventsource.properties }}
      {{ $key }}: {{ $val }}
      {{- end}}
      {{- if .Values.eventsource.resource.eventTypes }}
      eventTypes:
        {{- range $val := .Values.eventsource.resource.eventTypes }}
        - {{ $val }}
        {{- end }}
      {{- end}}
      {{- if .Values.eventsource.resource.filter }}
      filter:
        {{- if .Values.eventsource.resource.filter.afterStart }}
        afterStart: {{ .Values.eventsource.resource.filter.afterStart }}
        {{- end}}
        {{- if .Values.eventsource.resource.filter.afterStart }}
        labels:
          {{- range $val := .Values.eventsource.resource.filter.labels }}
          - key: {{ (split ":" $val)._0 }}
            value: {{ (split ":" $val)._1 }}
          {{- end }}
        {{- end}}
      {{- end}}
  {{- end }}
  template:
    metadata:
      labels:
      {{- include "gravity-workflow.labels" $ | nindent 8 }}
    {{- if .Values.eventsource.resource }}
    serviceAccountName: {{ .Values.eventsource.resource.serviceAccountName }}
    {{- end }}
    # serviceAccountName: {{ $appname }}-eventsource
