{{- $appname := include "gravity-workflow.name" . }}

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ $appname }}
spec:
  {{- if eq $.Values.eventsource.type "sqs" }}
  sqs:
    default:
      {{- range $key, $val := .Values.eventsource.properties }}
      {{- if eq $key "queue"}}
      queue: {{ (split ":" $val)._5 }}
      {{- else }}
      {{ $key }}: {{ $val }}
      {{- end}}
      {{- end }}
      # temporary block...
      accessKey:
        key: accesskey
        name: aws-secret-dev
      secretKey:
        key: secretkey
        name: aws-secret-dev
  {{- end }}
  {{- if eq $.Values.eventsource.type "azureEventsHub" }}
  azureEventsHub:
    default:
      {{- range $key, $val := .Values.eventsource.properties }}
      {{ $key }}: {{ $val }}
      {{- end }}
      sharedAccessKeyName:
        name: {{ .Values.azuresecret.sharedAccessKeyName.name }} 
        key: {{ .Values.azuresecret.sharedAccessKeyName.key }} 
      sharedAccessKey:
        name: {{ .Values.azuresecret.sharedAccessKey.name }} 
        key: {{ .Values.azuresecret.sharedAccessKey.key }} 
  {{- end }}
  template:
    metadata:
      labels:
      {{- include "gravity-workflow.labels" $ | nindent 8 }}
    # serviceAccountName: {{ $appname }}-eventsource
