{{- $appname := include "gravity-workflow.name" . }}

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ $appname }}
spec:
  sqs:
    default:
      {{- range $key, $val := .Values.eventsource.properties }}
      {{- if eq $key "queue"}}
      queue: {{ (split ":" $val)._5 }}
      {{- else }}
      {{ $key }}: {{ $val }}
      {{- end}}
      {{- end }}
      region: {{ .Values.aws.region }}
  template:
    metadata:
      labels:
      {{- include "gravity-workflow.labels" $ | nindent 8 }}
    serviceAccountName: {{ $appname }}-eventsource
