{{- $appname := include "gravity-workflow.name" . }}

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ $appname }}
spec:
  {{- if eq $.Values.type "sqs" }}
  sqs:
    default:
      {{- range $key, $val := .Values.properties }}
      {{- if eq $key "queue"}}
      queue: {{ (split ":" $val)._5 }}
      {{- else }}
      {{ $key }}: {{ $val }}
      {{- end}}
      {{- end }}
      {{- if .Values.awsSecret }}
      accessKey:
        key: {{ .Values.awsSecret.accessKey.key }}
        name: {{ .Values.awsSecret.accessKey.name }}
      secretKey:
        key: {{ .Values.awsSecret.secretKey.key }}
        name: {{ .Values.awsSecret.secretKey.name }}
      {{- end }}
  {{- end }}
  {{- if eq $.Values.type "azureEventsHub" }}
  azureEventsHub:
    default:
      {{- toYaml .Values.properties | nindent 6 }}
      sharedAccessKeyName:
        name: {{ .Values.azureSecret.sharedAccessKeyName.name }} 
        key: {{ .Values.azureSecret.sharedAccessKeyName.key }} 
      sharedAccessKey:
        name: {{ .Values.azureSecret.sharedAccessKey.name }} 
        key: {{ .Values.azureSecret.sharedAccessKey.key }} 
  {{- end }}
  {{- if eq $.Values.type "calendar" }}
  calendar:
    default:
      {{- toYaml .Values.properties | nindent 6 }}
  {{- end }}
  {{- if eq $.Values.type "redis" }}
  redis:
    default:
      {{- toYaml .Values.properties | nindent 6 }}
      password:
        name: {{ .Values.redisSecret.name  }}
        key: {{ .Values.redisSecret.key  }}
      namespace: {{ .Values.redisSecret.namespace  }}
  {{- end }}
  {{- if eq $.Values.type "kafka" }}
  kafka:
    default:
      {{- toYaml .Values.properties | nindent 6 }}
      {{- if .Values.kafka }}
      connectionBackoff:
        {{- toYaml $.Values.kafka.connectionBackoff | nindent 8}}
      sasl:
        {{- toYaml $.Values.kafka.sasl | nindent 8}}
      tls:
        insecureSkipVerify: true
      {{- end}}
  {{- end }}
  {{- if eq $.Values.type "resource" }}
  resource:
    default:
      namespace: {{ .Values.properties.namespace }}
      group: {{ .Values.properties.group }}
      version: {{ .Values.properties.version }}
      resource: {{ .Values.properties.resource }}
      eventTypes:
      {{- range $key, $val := .Values.properties.eventTypes }}
        - {{ $val }}
      {{- end }}
      filter:
        afterStart: {{ .Values.afterStart }}
        {{- if .Values.properties.filter.labels }}
        labels:
          {{- range $val := .Values.properties.filter.labels}}
          - key: {{ (split ":" $val)._0 }}
            value: {{ (split ":" $val)._1 }}
          {{- end }}
        {{- end}}
  {{- end }}
  template:
    metadata:
      labels:
      {{- include "gravity-workflow.labels" $ | nindent 8 }}
    {{- if eq $.Values.type "resource" }}
    serviceAccountName: {{ .Values.properties.serviceAccountName }}
    {{- end }}
