apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ .Values.eventsource.name }}
spec:
  {{ .Values.eventsource.type }}:
    {{ .Values.eventsource.eventName }}:
      jsonBody: {{ .Values.eventsource.jsonBody }}
      {{- if .Values.eventsource.accessKey }}
      accessKey:
        key: {{ .Values.eventsource.accessKey.key }}
        name: {{ .Values.eventsource.accessKey.name }}
      {{- end }}
      {{- if .Values.eventsource.secretKey }}
      secretKey:
        key: {{ .Values.eventsource.secretKey.key }}
        name: {{ .Values.eventsource.secretKey.name }}
      {{- end }}
      region: {{ .Values.eventsource.region }}
      queue: {{ .Values.eventsource.queue }}
      waitTimeSeconds: {{ .Values.eventsource.waitTimeSeconds }}
      {{- if .Values.eventsource.roleARN }}
      roleARN: {{ .Values.eventsource.roleARN }}
      {{- end }}
      {{- if .Values.eventsource.queueAccountId }}
      queueAccountId: {{ .Values.eventsource.queueAccountId }}
      {{- end }}
      {{- if .Values.eventsource.DLQ }}
      DLQ: {{ .Values.eventsource.DLQ }}
      {{- end }}
      {{- if .Values.eventsource.Endpoint }}
      Endpoint: {{ .Values.eventsource.Endpoint }}
      {{- end }}
  {{- if .Values.eventsource.template }}
  template:
    metadata:
      labels:
      {{- include "gravity-workflow.labels" $ | nindent 8 }}
    {{- if .Values.eventsource.template.serviceAccountName }}
    serviceAccountName: {{ .Values.eventsource.template.serviceAccountName }}
    {{- end }}
  {{- end }}
