{{- if .Values.workflows}}
{{- $appname := include "gravity-workflow.name" . }}
{{- $ns  := .Values.sensor.namespace }}

{{- range $cri, $cr := .Values.sensor.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $appname }}-{{ $cri }}
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $cr }}
subjects:
  - kind: ServiceAccount
    name: {{ $appname }}-sensor
{{- end }}
{{- end }}
