{{- $fullname := include "gravity-workflow.fullname" . }}
{{- $name := include "gravity-workflow.name" . }}
{{- if .Values.sensor}}
{{- range $i, $configmap := .Values.sensor.configmaps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ $fullname }}-{{ $i }}
spec:
  template:
    serviceAccountName: {{ $fullname }}-sensor
  dependencies:
    - name: default-dep
      eventSourceName: {{ $fullname }}
      eventName: default
  triggers:
    - template:
        name: {{ $fullname }}-trigger
        argoWorkflow:
          operation: submit
          args: ["--labels", "argocd.argoproj.io/instance={{ $name }}"]
          source:
            configmap:
              {{- range $key, $val := $configmap }}
              {{ $key }}: {{ $val }}
              {{- end }}
          parameters:
            - src:
                dependencyName: default-dep
                dataKey:  body
              dest: spec.arguments.parameters.0.value
{{- end }}
{{- end }}
