{{- $appname := include "app.fullname" . }}

{{- if .Values.workflows }}
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ $appname }}
spec:
  template:
    serviceAccountName: {{ $appname }}
  dependencies:
    - name: default
      eventSourceName: {{ $appname }}
      eventName: default
  triggers:
    {{- range $wfi, $wf := .Values.workflows }}
    - template:
        name: {{$appname}}-{{$wf.name}}-trigger
        argoWorkflow:
          operation: submit
          source:
            configmap:
              name: {{ $wf.configMapName }}
              key: {{ default "template" $wf.configMapKey }}
          parameters:
            - src:
                dependencyName: default
                dataKey: body
              dest: spec.arguments.parameters.{{ $wf.argIndex | default 0 }}.value
    {{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $appname }}-sensor
  labels:
    {{- include "app.labels" . | nindent 4 }}

{{- range $cri, $cr := .Values.sensor.clusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $appname }}-{{ $cri }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $cr }}
subjects:
  - kind: ServiceAccount
    name: {{ $appname }}-sensor
{{- end }}

{{- end }}