{{- $fullname := include "gravity-workflow.fullname" . }}
{{- if .Values.sensor}}
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ $fullname }}
spec:
  template:
    serviceAccountName: {{ $fullname }}-sensor
  dependencies:
    - name: default-dep
      eventSourceName: {{ $fullname }}
      eventName: default
  triggers:
    - template:
        name: {{ $fullname }}-trigger
        argoWorkflow:
          operation: submit
          source:
            configmap:
              {{- range $key, $val := .Values.sensor.configmap }}
              {{ $key }}: {{ $val }}
              {{- end }}
          parameters:
            - src:
                dependencyName: default-dep
                dataKey:  body
              dest: spec.arguments.parameters.0.value
{{- end }}
