{{- $appname := include "gravity-workflow.name" . }}
{{- if .Values.sensors}}
{{- range $i, $sensor := .Values.sensors }}
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ $appname }}-{{ $sensor.name }}
spec:
  template:
    serviceAccountName: {{ $appname }}-sensor
  dependencies:
    - name: default-dep
      eventSourceName: {{ $appname }}
      eventName: default
  triggers:
    - template:
        name: {{ $appname }}-trigger
        argoWorkflow:
          operation: submit
          args: ["--labels", "gravity.invisibl.io/instance={{ $appname }}"]
          source:
            configmap:
              {{- range $key, $val := $sensor.configmap }}
              {{ $key }}: {{ $val }}
              {{- end }}
          parameters:
            - src:
                dependencyName: default-dep
                dataKey:  body
              dest: spec.arguments.parameters.0.value
{{- end }}
{{- end }}
