{{- $fullname := include "gravity-workflow.fullname" . }}
{{- if .Values.sensor}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}-sensor
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gravity-workflow.labels" . | nindent 4 }}
{{- end }}
