{{- $appname := include "gravity-workflow.name" . }}
{{- if .Values.sensors}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $appname }}-sensor
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gravity-workflow.labels" . | nindent 4 }}
{{- end }}
