{{- $appname := include "gravity-workflow.name" . }}
{{- if .Values.workflows}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $appname }}-sensor
  namespace: {{ .Values.sa.namespace }}
  labels:
    {{- include "gravity-workflow.labels" . | nindent 4 }}
{{- end }}
