{{- $appname := include "gravity-workflow.name" . }}

{{- if .Values.identity.create }}
---
apiVersion: identity-manager.io/v1alpha1
kind: WorkloadIdentity
metadata:
  name: {{ $appname }}
  labels:
    {{- include "gravity-workflow.labels" $ | nindent 4 }}
spec:
  aws:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::{{ .Values.infra.id }}:oidc-provider/oidc.eks.{{ .Values.infra.region }}.amazonaws.com/id/{{ .Values.kube.oidc.id }}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "oidc.eks.{{ .Values.infra.region }}.amazonaws.com/id/{{ .Values.kube.oidc.id }}:sub":"system:serviceaccount:{{ .Release.Namespace }}:{{ $appname }}-eventsource"
              }
            }
          }
        ]
      }
    inlinePolicies:
      sqs-read-0: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "sqs:GetQueueUrl",
                "sqs:ReceiveMessage",
                "sqs:DeleteMessage"
              ],
              "Resource": [
                "*"
              ]
            }
          ]
        }
    maxSessionDuration: 3600
    path: "/"
    pods:
      - matchLabels:
          {{- include "gravity-workflow.selectorLabels" . | nindent 10 }}
    serviceAccounts:
      - action: Create
        name: "{{ $appname }}-eventsource"
        namespace: {{ .Release.Namespace }}
  description: 'identity for eventsource in argoapp: {{ $appname }}'
  name: {{ $appname }}
  provider: AWS
{{- end }}