
# # workflow id
# id: ""
# # workload instance (resource apply name)
# instance: "1"
# component: ""
# partOf: ""
# #managedBy: ""
# createdBy: ""
# project: ""

# # global
# infra: ~
# kube: ~

# # identity
# identity:
#   create: true

# # eventsource
# type: ""
# properties: {}

# # workflows
# workflows: []

sensor:
  clusterRoles:
    - operate-job-role
    # - argo-workflows-role

kafka:
  connectionBackoff:
    duration: 10s
    steps: 5
    factor: 2
    jitter: 0.2

id: es-kafka-1
identity:
  create: false
# infra:
#   id: ""
#   props: {}
#   provider: Azure
#   region: eastus
# instance: wrkflw-dev-es-kafka-1-f826f265
# kube:
#   engine: AKS
#   name: dev-devaks-b98277ab
#   oidc:
#     id: ""
#   uint32: "1560134030"
#   version: 1.21.9
# monit:
#   enabled: false
# project: dev
# properties:
#   partition: "0"
#   sasl:
#     mechanism: SCRAM-SHA-256
#     passwordSecret:
#       key: password
#       name: kafka-access-es-kafka-1
#     userSecret:
#       key: user
#       name: kafka-access-es-kafka-1
#   topic: ajf18st7-default
#   url: moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
# type: Kafka
# workflows:
# - configMapKey: template
#   configMapName: es-kafka-1-workflow-whalesay
#   name: wrkflw-kafka-1

# infra:
#   id: ""
#   props: {}
#   provider: Azure
#   region: eastus
# instance: wrkflw-dev-es-interval-1-d6f0d25b
# type: Calendar
# properties:
#   interval: 1m
# jobs:
# - configMapKey: template
#   configMapName: job-nginx
#   name: gravity-job-calendar-1
# kube:
#   engine: AKS
#   name: dev-devaks-b98277ab
#   oidc:
#     id: ""
#   uint32: "1560134030"
#   version: 1.21.9
# monit:
#   enabled: false
# project: dev

# id: es-interval-1
# identity:
#   create: false
# infra:
#   id: ""
#   props: {}
#   provider: Azure
#   region: eastus
# instance: wrkflw-dev-es-interval-1-ebf7c28f
# kube:
#   engine: AKS
#   name: dev-dev2-workload-352c2412
#   oidc:
#     id: ""
#   uint32: "469953889"
#   version: 1.23.8
# monit:
#   enabled: false
# project: dev
# properties:
#   interval: 2m
#   userPayload: hello
# type: Calendar
